version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo_container
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: node_app
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"

volumes:
  mongo-data:
