services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data:
